version: '2.4'
services:
  # Description: Jaeger all-in-one instance
  # (https://www.jaegertracing.io/docs/1.17/getting-started/#all-in-one) for distributed tracing.
  #
  # Disk: none
  # Ports exposed to other Sourcegraph services: 5778/TCP 6831/UDP 6832/UDP 14250/TCP 4320/UDP 4321/UDP
  # Ports exposed to the public internet: none
  # Ports exposed to site admins only: 16686/HTTP
  #
  jaeger:
    container_name: jaeger
    image: 'index.docker.io/sourcegraph/jaeger-all-in-one:5.10.3940@sha256:d830a8c3e8c2be841de04118664f01710fa75d22f4302351309cb39932eee936'
    cpus: 0.5
    mem_limit: '512m'
    ports:
      # Query port
      - '0.0.0.0:16686:16686'
      # Collector port
      - '0.0.0.0:14250:14250'
      - '0.0.0.0:4320:4320' # gRPC
      - '0.0.0.0:4321:4321' # HTTP
      # Agent ports
      - '0.0.0.0:5778:5778'
      - '0.0.0.0:6831:6831'
      - '0.0.0.0:6832:6832'
    networks:
      - sourcegraph
    restart: always
    command: [
      '--memory.max-traces=20000',
      "--sampling.strategies-file=/etc/jaeger/sampling_strategies.json",
      "--collector.otlp.enabled",
      "--collector.otlp.grpc.host-port=:4320",
      "--collector.otlp.http.host-port=:4321"
    ]

  # Configure collector to send traces to Jaeger
  otel-collector:
    environment:
      - JAEGER_HOST=jaeger
      - JAEGER_OTLP_GRPC_PORT=4320
      - JAEGER_OTLP_HTTP_PORT=4321
    command: ['--config', '/etc/otel-collector/configs/jaeger.yaml']

  # Let frontend proxy to Jaeger interface
  sourcegraph-frontend-0:
    environment:
      - 'JAEGER_SERVER_URL=http://jaeger:16686'

  sourcegraph-frontend-internal:
    environment:
      - 'JAEGER_SERVER_URL=http://jaeger:16686'
