---
- labels:
    job: node
  targets:
    - cadvisor:8080
    - sourcegraph-frontend-internal:6060
- labels:
    job: github-proxy
  targets:
    - github-proxy:6060
- labels:
    job: repo-updater
  targets:
    - repo-updater:6060
- labels:
    job: worker
  targets:
    - worker:6060
- labels:
    job: worker-executors
  targets:
    - worker:6996
- labels:
    job: node
  targets:
    - syntect-server:6060
- labels:
    job: precise-code-intel-worker
  targets:
    - precise-code-intel-worker:6060
    # Add new entries here for every searcher/symbol/gitserver replica.
- labels:
    job: zoekt-indexserver
  targets:
    - zoekt-indexserver-0:6072
- labels:
    job: sourcegraph-frontend
  targets:
    - sourcegraph-frontend-0:6060
- labels:
    job: gitserver
  targets:
    - gitserver-0:6060
- labels:
    job: searcher
  targets:
    - searcher-0:6060
- labels:
    job: symbols
  targets:
    - symbols-0:6060
- labels:
    job: pgsql
  targets:
    - pgsql-exporter:9187
- labels:
    job: codeintel-db
  targets:
    - codeintel-db-exporter:9187
- labels:
    job: codeinsights-db
  targets:
    - codeinsights-db-exporter:9187
- labels:
    job: redis-cache
  targets:
    - redis-cache:9121
- labels:
    job: redis-store
  targets:
    - redis-store:9121
