---
- labels:
    job: node
  targets:
    # Uncomment these if you want to monitor PostgreSQL / Redis via Prometheus.
    #- pgsql:9187
    #- redis-cache:9121
    #- redis-store:9121
    - cadvisor:8080
    - sourcegraph-frontend-internal:6060
    - github-proxy:6060
    - management-console:6060
    - query-runner:6060
    - repo-updater:6060
    - zoekt-indexserver:6072
    - syntect-server:6060
    - lsif-server:3186
    - lsif-server:3187
    # Add new entries here for every searcher/symbol/gitserver replica.
    - sourcegraph-frontend-0:6060
    - gitserver-0:6060
    - searcher-0:6060
    - symbols-0:6060
    - replacer-0:6060
