---
- labels:
    job: node
  targets:
    # Uncomment these if you want to monitor PostgreSQL / Redis via Prometheus.
    #- pgsql:9187
    #- codeintel-db:9187
    #- codeinsights-db:9187
    #- redis-cache:9121
    #- redis-store:9121
- labels:
    job: node
  targets:
    - cadvisor:8080
    - sourcegraph-frontend-internal:6060
- labels:
    job: github-proxy
  targets:
    - github-proxy:6060
- labels:
    job: query-runner
  targets:
    - query-runner:6060
- labels:
    job: repo-updater
  targets:
    - repo-updater:6060
- labels:
    job: worker
  targets:
    - worker:6060
- labels:
    job: node
  targets:
    - syntect-server:6060
- labels:
    job: precise-code-intel-worker
  targets:
    - precise-code-intel-worker:6060
    # Add new entries here for every searcher/symbol/gitserver replica.
- labels:
    job: zoekt-indexserver
  targets:
    - zoekt-indexserver-0:6072
- labels:
    job: sourcegraph-frontend
  targets:
    - sourcegraph-frontend-0:6060
- labels:
    job: gitserver
  targets:
    - gitserver-0:6060
- labels:
    job: searcher
  targets:
    - searcher-0:6060
- labels:
    job: symbols
  targets:
    - symbols-0:6060
    - postgres-exporter:9187

