# Prometheus global config
global:
  scrape_interval: 30s # Scrape services for updated metrics every 30s. Default is 1m.
  evaluation_interval: 30s # Evaluate rules every 30s. Default is 1m.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # deploy-sourcegraph-docker does not yet use prometheus alerts
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "*_rules.yml"
  - "/sg_prometheus_add_ons/*_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape for metrics:
scrape_configs:
  # Scrape prometheus itself for metrics.
  - job_name: "prometheus"
    static_configs:
        - targets: ["localhost:9090"]

  - job_name: "sg"
    file_sd_configs:
      - files:
          - "/sg_prometheus_add_ons/*_targets.yml"

## Note: the content above is taken from sourcegraph/sourcegraph/docker-images/prometheus/config/prometheus.yml
## I'm not currently sure how to configure the below in an external file via file_sd_configs.
##
## TODO(eric,uwedeportivo) - find a way to express what's below in an extensible way so we can 
## just add config files in this directory instead of overwriting the entire main configuration.

  - job_name: federate
    honor_labels: true
    metrics_path: /federate
    params:
      'match[]':
        - '{__name__=~"lsif_.*"}'

    static_configs:
      - targets:
        - lsif-server:9090
